version: "3"

services:
  client-sport-db:
    # <<: *default-logging
    image: postgres:12
    container_name: "client-sport-db"
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - client-sport-db:/var/lib/postgresql/data
    environment:
      # POSTGRES_USER: root
      POSTGRES_PASSWORD: IIIdevops123!
      POSTGRES_DB: postgres

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  client-sport-redis:
    # <<: *default-logging
    image: redis:6.2.11
    container_name: "client_redis"
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=IIIdevops123!
    # command: redis-server --save 20 1 --loglevel warning --requirepass IIIdevops123!
    # volumes:
    #   - cache:/data
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  client-mongodb:
    image: mongo:4
    container_name: "client_mongo"
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./docker_compose_file/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: iv9614
      MONGO_INITDB_ROOT_PASSWORD: IIIdevops123!

  client-api:
    # <<: *default-logging
    image: sport-client-api:1.0.1
    restart: always
    container_name: "sport-client-api"
    # restart: on-failure
    depends_on:
      client-sport-db:
        condition: service_started
      client-sport-redis:
        condition: service_started
      client-mongodb:
        condition: service_started
    ports:
      - "10010:10009" #"${III_PORT}:10009"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:IIIdevops123!@client-sport-db:5432/client #client-sport-db:5432
      SQLALCHEMY_TRACK_MODIFICATIONS: false
      MONGODB_URL: mongodb://iv9614:IIIdevops123!@client-mongodb:27017/ #10.20.0.43:27017
      JWT_SECRET_KEY: x4QkyoxjiT7oQmVnv3_i
      WTF_CSRF_CHECK_DEFAULT: false
      JSON_AS_ASCII: false
      ADMIN_INIT_LOGIN: sysadmin
      ADMIN_INIT_EMAIL: tech@iii-devops.org
      ADMIN_INIT_PASSWORD: IIIdevops123!
      DEPLOY_CERTIFICATE_ROOT_PATH:
      DEBUG: true
      USE_RELOADER: true
      DOCUMENT_LEVEL: private
      REDIS_BASE_URL: client-sport-redis:6379
      ORGANIZE_DEFAULT_PASSWORD: IIISport12345!
      BRANCH: develop
      POD_SERVICE: sport-data-api-develop-serv-svc
      SUV_IP: 45.76.50.161
      SUV_USER: root
      SUV_PASSWORD: G9eBmLpbq?@-EsG
      API_URL: https://127.0.0.1
      PYTHONHASHSEED: 0
      MASTER_URL: https://sport-data-api-dev-client.ingress-devops.data-sports.org/
      MAX_NEXT_LOGIN_SEC: 900
      MAX_ACCOUNT_RETRY_TIMES: 5
      MAX_IP_RETRY_TIMES: 20
      BLOCK_IP: 127.0.0.2
    # volumes:
    #   - iii-devops-lite-file:/opt/nfs
    #   - iii-devops-lite-log:/logs

  client-ui:
    # <<: *default-logging
    image: harbor-devops.data-sports.org/sportdata-ui/distribute-module:1.0.0
    container_name: "sport-client-ui"
    restart: always
    labels:
      - "autoheal=true"
    depends_on:
      - client-api
    ports:
      - "80:80"
    environment:
      API_URL: http://client-api:10009/ # http://10.20.0.43:10010/
    healthcheck:
      test: curl --fail http://localhost/prod-api/swagger-ui/ || exit 1
      interval: 10s
      timeout: 1s
      retries: 5

volumes:
  client-sport-db:
    driver: local
  client-sport-redis:
    driver: local
  client-mongodb:
    driver: local
