version: "3"

services:
  client-sport-db:
    # <<: *default-logging
    image: postgres:12
    container_name: "client-sport-db"
    restart: always
    user: postgres
    ports:
      - "${SPORT_DB_PORT}:5432"
    volumes:
      - client-sport-db:/var/lib/postgresql/data
    environment:
      # POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  client-sport-redis:
    # <<: *default-logging
    image: redis:6.2.11
    container_name: "client_redis"
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=IIIdevops123!
    # command: redis-server --save 20 1 --loglevel warning --requirepass IIIdevops123!
    # volumes:
    #   - cache:/data
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  client-mongodb:
    image: mongo:4
    container_name: "client_mongo"
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - client-mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  client-api:
    # <<: *default-logging
    image: iiiorg/sport-api-client:develop
    restart: always
    container_name: "sport-client-api"
    # restart: on-failure
    depends_on:
      client-sport-db:
        condition: service_started
      client-sport-redis:
        condition: service_started
      client-mongodb:
        condition: service_started
    ports:
      - "${SPORT_PORT}:10009"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:${POSTGRES_PASSWORD}@client-sport-db:${SPORT_DB_PORT}/client #client-sport-db:5432
      SQLALCHEMY_TRACK_MODIFICATIONS: "false"
      MONGODB_URL: mongodb://${MONGO_ROOT}:${MONGO_PASSWORD}@client-mongodb/ #10.20.0.43:27017
      JWT_SECRET_KEY: x4QkyoxjiT7oQmVnv3_i
      WTF_CSRF_CHECK_DEFAULT: "false"
      JSON_AS_ASCII: "false"
      ADMIN_INIT_LOGIN: sysadmin
      ADMIN_INIT_EMAIL: tech@iii-devops.org
      ADMIN_INIT_PASSWORD: IIIdevops123!
      DEPLOY_CERTIFICATE_ROOT_PATH:
      DEBUG: "true"
      USE_RELOADER: "true"
      DOCUMENT_LEVEL: private
      REDIS_BASE_URL: client-sport-redis:6379
      ORGANIZE_DEFAULT_PASSWORD: IIISport12345!
      BRANCH: develop
      POD_SERVICE: sport-data-api-develop-serv-svc
      SUV_IP: 45.76.50.161
      SUV_USER: root
      SUV_PASSWORD: G9eBmLpbq?@-EsG
      API_URL: http://${IP_ADDRESS}:10009/
      PYTHONHASHSEED: 0
      MASTER_URL: ${MASTER_URL}
      MAX_NEXT_LOGIN_SEC: 900
      MAX_ACCOUNT_RETRY_TIMES: 5
      MAX_IP_RETRY_TIMES: 20
      BLOCK_IP: 127.0.0.2
      # volumes:
      #   - iii-devops-lite-file:/opt/nfs
      # - client-api-logs:/logs

  client-ui:
    # <<: *default-logging
    image: iiiorg/sport-ui-client:develop
    container_name: "sport-client-ui"
    restart: always
    labels:
      - "autoheal=true"
    depends_on:
      - client-api
    ports:
      - "80:80"
    environment:
      API_URL: http://client-api:10009/ # http://10.20.0.43:10010/
    healthcheck:
      test: curl --fail http://localhost/prod-api/swagger-ui/ || exit 1
      interval: 10s
      timeout: 1s
      retries: 5

volumes:
  client-sport-db:
    driver: local
  client-sport-redis:
    driver: local
  client-mongodb:
    driver: local
  # client-api-logs:
  #   driver: local
