# !!! DO NOT USE THIS FILE DIRECTLY !!!
# This file is used by iiidevops-cli to generate docker-compose.yaml
# Please only run docker-compose.yaml

version: "3"

services:
  backend-base:
    image: harbor-devops.data-sports.org/sport-api-slave/develop:1.0.0
    restart: always
    # volumes:
    #   - ./HEAD.env:/env/HEAD.env
    # We don't share depends_on with other services because it's docker limit
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:IIIdevops123!@10.20.0.43:5432/client #client-sport-db:5432
      SQLALCHEMY_TRACK_MODIFICATIONS: false
      MONGODB_URL: mongodb://iv9614:IIIdevops123!@10.20.0.43:27017/ #10.20.0.43:27017
      JWT_SECRET_KEY: x4QkyoxjiT7oQmVnv3_i
      WTF_CSRF_CHECK_DEFAULT: false
      JSON_AS_ASCII: false
      ADMIN_INIT_LOGIN: sysadmin
      ADMIN_INIT_EMAIL: tech@iii-devops.org
      ADMIN_INIT_PASSWORD: IIIdevops123!
      DEPLOY_CERTIFICATE_ROOT_PATH:
      DEBUG: true
      USE_RELOADER: true
      DOCUMENT_LEVEL: private
      REDIS_BASE_URL: 10.20.0.43:6379
      ORGANIZE_DEFAULT_PASSWORD: IIISport12345!
      BRANCH: develop
      POD_SERVICE: sport-data-api-develop-serv-svc
      SUV_IP: 45.76.50.161
      SUV_USER: root
      SUV_PASSWORD: G9eBmLpbq?@-EsG
      API_URL: https://127.0.0.1
      PYTHONHASHSEED: 0
      MASTER_URL: http://127.0.0.1:10009
      MAX_NEXT_LOGIN_SEC: 900
      MAX_ACCOUNT_RETRY_TIMES: 5
      MAX_IP_RETRY_TIMES: 20
      BLOCK_IP: 127.0.0.2
